version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/typescript"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
  - package-ecosystem: "nuget"
    directory: "/csharp"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
