version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/typescript"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
  - package-ecosystem: "nuget"
    directory: "/csharp/src/TodoApi"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
  - package-ecosystem: "nuget"
    directory: "/csharp/tests/TodoApi.Tests"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
  - package-ecosystem: "gomod"
    directory: "/go"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
